### ISSUE TITLE
[Android] int com.twilio.chat.ChatClient$SynchronizationStrategy.getValue() on null object reference

### ISSUE THREAD

**Issue by shubhangi-asgola** [ccm-innovation/react-native-twilio-chat#13]
I am using RN0.42
I followed the installation steps for android. I am getting following error after client.initialize() where client is (client = new Client)[import {Client} from 'react-native-twilio-chat']
'attempt to call virtual method com.twilio.chat.ChatClient.$SynchronizationStrategy.getValue() on a null objetct reference'

I then followed the SDK installation steps from 'https://www.twilio.com/docs/api/chat/sdks' and added below lines in my app build.gradle file:
```
compile 'com.twilio:chat-android:0.12.2'
compile 'com.twilio:accessmanager-android:0.1.0'
```
After that the app crashes with message 'Unfortunately [AppName] has stopped working'

My build.gradle has:
```
    compileSdkVersion 23
    buildToolsVersion "23.0.1"
    dexOptions {
        jumboMode = true
        javaMaxHeapSize "2048M"
     }
defaultConfig {
        minSdkVersion 19
        targetSdkVersion 22
        versionCode 22
        versionName "3.0.4"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
dependencies {
    //compile project(':react-native-twilio-chat')
    compile project(':RCTTwilioChat')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.twilio:chat-android:0.12.2'
    compile "com.twilio:accessmanager-android:0.1.0"
}
```

**Comment by Kabangi** [comment]
@shubhangi-asgola was also getting this error but got it fixed by wrapping my calls within in a setTimeout, like this:-

    this.twilioClient.onClientSynchronized = () => {
        setTimeout(() => {
            //Register Push tokens to receive Push notifications.
            if(this.user.device_tokens && this.user.device_tokens.length > 0){
                this.user.device_tokens.forEach((token) => {
                   this.twilioClient.register(token);
               })
           }
      this.twilioClient.getUserChannels().then(async (channels) => {
        channels = channels.items;
        if(channels.length > 0){
          this.totalChannels = channels.length;
          await this.saveChannelsLocally(channels);
          channels.forEach(ch => this.setupChannel(ch));
        }else{
          //TODO. Delete all existings conversations and their messages
          //that are synchronised since they seem not to exist on twilio any more.
          //Alternatively recreate them again.
          this.initialized$.onNext(true);
        }
      });
    },10);
}

**Comment by shubhangi-asgola** [comment]
**@Kabani**  Thank you for giving some time to reply. However, I am still getting the same error. Are you using below lines in dependencies.

compile 'com.twilio:chat-android:0.12.2'
compile "com.twilio:accessmanager-android:0.1.0"

Without including above in dependencies I think it breaks at point where I am trying to initialize the client.

**Comment by bradbyte** [comment]
@shubhangi-asgola I'm sorry you are experiencing issues.. are you able to see anything in Android Studio when it crashes? it might contain some more details... 

Try removing these dependencies from your settings.gradle file, as these will be imported through the package. 
```
compile 'com.twilio:chat-android:0.12.2'
compile "com.twilio:accessmanager-android:0.1.0"
```.

I noticed you commented out package `react-native-twilio-chat`? was that just for testing? While the Twilio SDK docs will tell you the instructions to integrate with a native app, you need to follow the installation notes on this package as it is different when incorporating with React Native.

**Comment by Kabangi** [comment]
@shubhangi-asgola This module is a wrapper for twilio sdks both ios and android. For installation you need to follow  the guides on docs for the module and not twilio modules. The module itself will import the respective twilio modules that it requires to work. 

Here is my dependencies list:-

```
dependencies {
    compile project(':react-native-twilio-chat') //By importing this am also importing 'com.twilio:chat-android:0.11.0'
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile ('com.google.android.gms:play-services-gcm:9.0.0') {
        force = true;
    }
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```

**Comment by bradbyte** [comment]
@shubhangi-asgola were you able to get this working?

**Comment by shubhangi-asgola** [comment]
@bradbumbalough I was not able to try it due to some work, will updated once I am through, probably by tomorrow or day after.
Regarding your previous comment, I have commented out react-native-twilio-chat from dependencies instead included RCTTwilioChat as suggested for the module in installation steps.

**Comment by shubhangi-asgola** [comment]
**@bradbumbalough** I am facing the problem only in Android. I am using a Windows system. React Native version : ^0.42.0".
I have followed the following steps:

In android/settings.gradle:

include ':RCTTwilioChat', ':app'
project(':RCTTwilioChat').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-twilio-chat/android')

In android/app/build.gradle:
...
dependencies {
    ...
    compile project(':RCTTwilioChat')
}

Register the module in MainApplication.java:

// import package
import com.bradbumbalough.RCTTwilioChat.RCTTwilioChatPackage;

...

// register package in getPackages()
@Override
protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new RCTTwilioChatPackage(),
        ... other packages
    );
}

In build.gradle

android {
    ....
    dexOptions {
        javaMaxHeapSize "2048M"
    }
    
    defaultConfig {
        ...
        minSdkVersion 19
        multiDexEnabled true
    }

I have also tried wrapping onClientSynchronized() inside setTimeout()

I get below error. Please point out if I am missing on something.


![image](https://cloud.githubusercontent.com/assets/10372934/24903570/71bf9476-1ecb-11e7-9435-497338e07637.png)

**Comment by Kabangi** [comment]
Still getting the error. Here is my stacktrace.

<img width="949" alt="screen shot 2017-04-18 at 10 38 31 am" src="https://cloud.githubusercontent.com/assets/8632600/25119529/3576b5f0-2423-11e7-9d1f-939f93053a6b.png">

**Comment by shubhangi-asgola** [comment]
**@Kabangi**  Are you trying to send attributed message?

**Comment by Kabangi** [comment]
@shubhangi-asgola  No just the ordinary message. Also noticed am getting this error when I do channel.getMembers

**Comment by bradbyte** [comment]
Sorry it's been so long to get back to you -- can you provide some examples of how you're implementing the client in your code?

**Comment by shubhangi-asgola** [comment]
**@bradbumbalough**  I am creating Client as:-
```js
const client = new Client(token);
```
Then on calling function
```js
          client.createChannel({
                   friendlyName: 'NAME',
                   uniqueName: channelSid,
                   type: Constants.TCHChannelType.Public
            })
```
it goes to createChannel function in Client.js where Constants is imported as

import Constants from './Constants';

The imported Constants has all the Constants required however they are in below format due to which when it tries to call a particular constant it doesn't get it as it is wrapped inside other object named default. For example if I want to access FriendlyName instead of accessing it as
Constants.TCHChannelOption.FriendlyName
I have to access it as:
Constants.default.TCHChannelOption.FriendlyName

![image](https://cloud.githubusercontent.com/assets/10372934/25136293/3e739a5c-2472-11e7-8060-bb6b7eadb7b5.png)

**Comment by bradbyte** [comment]
Hey guys, I'm so sorry I haven't been able to comment on here in awhile.

@shubhangi-asgola I'm not sure which version of the package you're using.. if you look here you can see that is not the way the exports are being done https://github.com/ccm-innovation/react-native-twilio-chat/blob/02e4facfc6136d592a86f65ce00ede1c2a69e671/lib/Client.js#L268.

However, I have found the issue as to why you are getting the `int com.twilio.chat.ChatClient$SynchronizationStrategy.getValue() on null object reference` error and will have it resolved shortly.

**Comment by bradbyte** [comment]
I believe this has been fixed in [`0.2.0`](https://github.com/ccm-innovation/react-native-twilio-chat/releases/tag/v0.2.0). Please update and reopen if it still occurs. Thank you!
